### PR TITLE
Remove TreeBuilder deprecation in Symfony 4.2

### PR DESCRIPTION
**Pull request by endelwar**

### CODE REVIEW

**Comment by endelwar** [comment]
@Nyholm is this mergeable?

**Comment by robob4him** [comment]
@Nyholm is there a release planned to include these changes?

**Comment by junaidbinfarooq** [comment]
@Nyholm I am waiting for the release too. Is there any plan to release this in the near future?

**Comment by petrosei** [comment]
@Nyholm I also need this releaded. I want to upgrade to Symfony 5.0 and will not be supported anymore in 5.0

**Comment by slunak** [comment]
+ 1 for the release.

In meanwhile one can add "cspoo/swiftmailer-mailgun-bundle": "dev-master" in composer json instead of bundle specific version. Note, this is not a solution but a workaround until release is there.

**Pull request merged**
