### PR TITLE
Symfony 5 and PHP 8 support

### PR DESCRIPTION
**Pull request by faizanakram99**
Made fork a few days ago for Symfony 5 and PHP 8 support

All tests run with this PR
Not sure about travis, no experience with it

### CODE REVIEW

**Comment by karensg** [comment]
Thanks for your PR, we fixed it in #88.

**Comment by faizanakram99** [comment]
> Thanks for your PR, we fixed it in #88.

Not sure whether to be happy or sad. I had made PR on January 6 and the other PR was made literally yesterday (after 9 months) :man_shrugging:

**Comment by karensg** [comment]
Hey @faizanakram99.
I just got access to the repository after contacting the owner. We tried to cherry-pick all the good stuff from all available PR's and added some more. If there is still something missing what you would like to have, please make another PR and I will merge it, no problem 🙌

**Comment by faizanakram99** [comment]
@karensg ah ok, cheers.

**Pull request closed without merging**
