### PR TITLE
Make sure to follow API docs

### LINKED ISSUE #11: CC/BCC is ignored when using MIME message
mailgun API to send MIME messages (used in this bundle) is pretty useless
see https://github.com/mailgun/mailgun-php/issues/81
STMP connection actually works

### PR DESCRIPTION
**Pull request by Nyholm**
The official documentation states that the second parameter of `Mailgun::sendMessage` should contain from, to, cc and bcc fields when needed. ([Ref](https://documentation.mailgun.com/user_manual.html#sending-via-api)) This PR verifies that if such fields exists in the message header we will use them as second parameter. 

~~This will not fix #11 but it will make sure that we do as the documentation suggests. (The issue in #11 relates to a bug on the API server, [ref](https://github.com/mailgun/mailgun-php/issues/81#issuecomment-98616213),)~~

### CODE REVIEW

**Comment by Nyholm** [comment]
@jessespears made a [comment](https://github.com/mailgun/mailgun-php/issues/81#issuecomment-99568829) on this. You should put all your recipients in the *to*. The mime file will take care of the rest. 

Also, we should not show *bcc* in the mime. 

This will fix #11.

**Comment by Nyholm** [comment]
Ping @tehplague, would you mind reviewing this?

**Comment by Nyholm** [comment]
Thank you for merging this.

**Comment by bencroker** [comment]
Released in 1.3.4.

**Pull request merged**
