### PR TITLE
Semantic change.

### PR DESCRIPTION
**Pull request by Nyholm**
We are not compatible with PHP 8. =)

### CODE REVIEW

**Comment by tehplague** [comment]
@Nyholm Actually, we don't know yet if we are compatible or not ;)

**Comment by OskarStark** [comment]
> @Nyholm Actually, we don't know yet if we are compatible or not ;)

but this should be checked by the maintainers after PHP 8.0 was released...

**Comment by Nyholm** [comment]
it is just a semantic change.

**Comment by Nyholm** [comment]
Thank you for the reviews.

**Pull request merged**
