### PR TITLE
Added configuration for endpoint - EU region has different endpoint URL

### PR DESCRIPTION
**Pull request by jskvara**
EU Region has different endpoint URL for API: `https://api.eu.mailgun.net`
https://help.mailgun.com/hc/en-us/articles/360007512013-Can-I-migrate-my-domain-to-EU- (Configuration Changes section)

### CODE REVIEW

**Comment by alister** [comment]
This looks useful, though I'd add a couple of things that would finish it - 

1. tests to ensure that what is in the config is sent to the underlying service, 
2. a note in the documentation about how to use it, including what happens if it's not there (ie, it's optional, and will just use the original US-based servers).

**Comment by jskvara** [comment]
I've added test and documentation, it should be ready to merge now.

**Comment by advancingu** [comment]
@Nyholm Any chance this can be merged? It's been sitting ready for six weeks.

**Comment by arkste** [comment]
any update on this?

**Comment by Nyholm** [comment]
Wohoo!

1.2.0 was just released.

**Pull request merged**
